# TCL File Generated by Component Editor 18.1
# Thu Oct 24 17:20:47 BRST 2019
# DO NOT MODIFY


# 
# tpm "Tree Parity Machine" v1.0
# Arthur Alexsander Martins Teodoro 2019.10.24.17:20:47
# Tree Parity Machine IP Driver.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module tpm
# 
set_module_property DESCRIPTION "Tree Parity Machine IP Driver."
set_module_property NAME tpm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Arthur Alexsander Martins Teodoro"
set_module_property DISPLAY_NAME "Tree Parity Machine"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tpm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tpm.vhd VHDL PATH ip/tpm/tpm.vhd TOP_LEVEL_FILE
add_fileset_file lfsr32.vhd VHDL PATH ip/tpm/lfsr32.vhd


# 
# parameters
# 
add_parameter K NATURAL 3
set_parameter_property K DEFAULT_VALUE 3
set_parameter_property K DISPLAY_NAME K
set_parameter_property K TYPE NATURAL
set_parameter_property K UNITS None
set_parameter_property K HDL_PARAMETER true
add_parameter N NATURAL 4
set_parameter_property N DEFAULT_VALUE 4
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE NATURAL
set_parameter_property N UNITS None
set_parameter_property N HDL_PARAMETER true
add_parameter L NATURAL 5
set_parameter_property L DEFAULT_VALUE 5
set_parameter_property L DISPLAY_NAME L
set_parameter_property L TYPE NATURAL
set_parameter_property L UNITS None
set_parameter_property L HDL_PARAMETER true
add_parameter RULE STRING hebbian
set_parameter_property RULE DEFAULT_VALUE hebbian
set_parameter_property RULE DISPLAY_NAME RULE
set_parameter_property RULE TYPE STRING
set_parameter_property RULE UNITS None
set_parameter_property RULE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_address address Input 8
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
add_interface_port avalon_slave_0 avs_read read Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

# Device tree generation
set_module_assignment embeddedsw.dts.vendor "dsa"
set_module_assignment embeddedsw.dts.compatible "dev,tpm"
set_module_assignment embeddedsw.dts.group "tpm"

